# Generated by Django 3.2.8 on 2021-10-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
