# Generated by Django 3.2.8 on 2021-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20211016_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Address',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
